### ISSUE TITLE
Unfetched attribute exception is thrown with many-to-many association

### ISSUE THREAD

**Issue by Flaurite** [Haulmont/jmix-data#102]
### Description
See forum: [topic](https://forum.jmix.io/t/tagpicker-problem-test-project-included/799)

### Steps to reproduce
1. Download demo project: [tagpickerproblem.zip](https://github.com/Haulmont/jmix-data/files/7640014/tagpickerproblem.zip)
2. Open Application -> Tag holder entities -> select and edit record
3. It seems the exception is thrown randomly, try to close and open editor a few times.

**Stacktrace**
```
java.lang.IllegalStateException: Cannot get unfetched attribute [tags] from detached object com.company.tagpickerproblem.entity.TagHolderEntity-f0800c08-27cd-6d4d-64bb-12dd49217f33 [detached].
	at org.eclipse.persistence.internal.indirection.UnitOfWorkValueHolder.throwUnfetchedAttributeException(UnitOfWorkValueHolder.java:326)
	at org.eclipse.persistence.internal.indirection.DatabaseValueHolder.getValue(DatabaseValueHolder.java:101)
	at org.eclipse.persistence.indirection.IndirectList.buildDelegate(IndirectList.java:275)
	at org.eclipse.persistence.indirection.IndirectList.getDelegate(IndirectList.java:458)
	at org.eclipse.persistence.indirection.IndirectList.toArray(IndirectList.java:864)
	at com.google.common.collect.ForwardingCollection.toArray(ForwardingCollection.java:123)
	at com.google.common.collect.ForwardingCollection.toArray(ForwardingCollection.java:123)
	at java.util.ArrayList.addAll(ArrayList.java:583)
	at io.jmix.ui.model.impl.CollectionContainerImpl.setItems(CollectionContainerImpl.java:101)
	at io.jmix.ui.model.impl.CollectionPropertyContainerImpl.setItems(CollectionPropertyContainerImpl.java:73)
	at io.jmix.ui.model.DataComponents.lambda$createCollectionContainer$2(DataComponents.java:154)
	at io.jmix.core.common.event.EventHub.publish(EventHub.java:170)
	at io.jmix.ui.model.impl.InstanceContainerImpl.fireItemChanged(InstanceContainerImpl.java:167)
	at io.jmix.ui.model.impl.InstanceContainerImpl.setItem(InstanceContainerImpl.java:100)
	at io.jmix.ui.model.impl.InstanceLoaderImpl.load(InstanceLoaderImpl.java:106)
	at io.jmix.ui.component.dataloadcoordinator.OnFrameOwnerEventLoadTrigger.load(OnFrameOwnerEventLoadTrigger.java:48)
	at io.jmix.ui.component.dataloadcoordinator.OnFrameOwnerEventLoadTrigger.lambda$new$0(OnFrameOwnerEventLoadTrigger.java:39)
	at io.jmix.core.common.event.EventHub.publish(EventHub.java:170)
	at io.jmix.ui.screen.Screen.fireEvent(Screen.java:124)
	at io.jmix.ui.screen.UiControllerUtils.fireEvent(UiControllerUtils.java:58)
	at io.jmix.ui.sys.ScreensImpl.fireScreenBeforeShowEvent(ScreensImpl.java:1361)
	at io.jmix.ui.sys.ScreensImpl.show(ScreensImpl.java:354)
	at io.jmix.ui.screen.Screen.show(Screen.java:306)
	at io.jmix.ui.action.list.EditAction.execute(EditAction.java:377)
	at io.jmix.ui.action.list.EditAction.actionPerform(EditAction.java:324)
	at io.jmix.ui.component.impl.AbstractTable.handleClickAction(AbstractTable.java:1384)
```

**Comment by kendovitskii** [comment]
Verified on
1.2.0 - SNAPSHOT
