### ISSUE TITLE
Lazy loading doens't work in master-detail editing screen

### ISSUE THREAD

**Issue by alexbudarov** [Haulmont/jmix-data#19]
Project attached:
[masdet.zip](https://github.com/Haulmont/jmix-data/files/5565813/masdet.zip)

In writer-edit.xml I forgot to include "Book.genre" property which is displayed in the table:
```
        <instance id="writerDc"
                  class="com.company.masdet.entity.Writer">
            <fetchPlan extends="_local">
                <property name="books" fetchPlan="_instance_name">
                    <property name="name"/>
                    <!--<property name="genre"/>-->
                </property>
            </fetchPlan>
            <loader/>
            <collection id="booksDc" property="books"/>
        </instance>
```

- launch app
- create one Book
- create one Writer, add book to writer
- reopen Writer for editing

exception occurs:
![image](https://user-images.githubusercontent.com/6158807/99648613-ad76a300-2a6c-11eb-9c5f-57b5c32eff43.png)

```
java.lang.IllegalStateException: Cannot get unfetched attribute [genre] from detached object com.company.masdet.entity.Book-4b0dbdf0-1d9c-c152-e5d6-ee55ba7aa63f [detached].
	at org.eclipse.persistence.internal.queries.EntityFetchGroup.onUnfetchedAttribute(EntityFetchGroup.java:100)
	at io.jmix.data.impl.JmixEntityFetchGroup.onUnfetchedAttribute(JmixEntityFetchGroup.java:67)
	at org.eclipse.persistence.internal.jpa.EntityManagerImpl.processUnfetchedAttribute(EntityManagerImpl.java:3027)
	at com.company.masdet.entity.Book._persistence_checkFetched(Book.java)
	at com.company.masdet.entity.Book._persistence_get_genre(Book.java)
	at com.company.masdet.entity.Book.getGenre(Book.java:32)
	at io.jmix.core.entity.BaseEntityEntry.getAttributeValue(BaseEntityEntry.java:73)
	at io.jmix.core.entity.EntityValues.getValue(EntityValues.java:90)
	at io.jmix.core.entity.EntityValues.getValueEx(EntityValues.java:121)
	at io.jmix.ui.component.data.table.ContainerTableItems.getItemValue(ContainerTableItems.java:116)
	at io.jmix.ui.component.table.TableItemWrapper.getPropertyValue(TableItemWrapper.java:81)
	at io.jmix.ui.component.table.TableItemPropertyWrapper.getValue(TableItemPropertyWrapper.java:37)
	at io.jmix.ui.component.impl.AbstractTable.formatCellValue(AbstractTable.java:1225)
	at io.jmix.ui.widget.JmixTable.formatPropertyValue(JmixTable.java:354)
	at io.jmix.ui.widget.JmixTable.getPropertyValue(JmixTable.java:269)
	at com.vaadin.v7.ui.Table.parseItemIdToCells(Table.java:2371)
	at com.vaadin.v7.ui.Table.getVisibleCellsNoCache(Table.java:2219)
	at com.vaadin.v7.ui.Table.refreshRenderedCells(Table.java:1762)
	at com.vaadin.v7.ui.Table.attach(Table.java:4276)
	at com.vaadin.server.AbstractClientConnector.attach(AbstractClientConnector.java:643)
	at com.vaadin.ui.AbstractComponent.attach(AbstractComponent.java:670)
	at com.vaadin.server.AbstractClientConnector.attach(AbstractClientConnector.java:643)
	at com.vaadin.ui.AbstractComponent.attach(AbstractComponent.java:670)
	at com.vaadin.server.AbstractClientConnector.attach(AbstractClientConnector.java:643)
	at com.vaadin.ui.AbstractComponent.attach(AbstractComponent.java:670)
	at com.vaadin.server.AbstractClientConnector.attach(AbstractClientConnector.java:643)
	at com.vaadin.ui.AbstractComponent.attach(AbstractComponent.java:670)
	at com.vaadin.ui.AbstractComponent.setParent(AbstractComponent.java:571)
	at com.vaadin.ui.AbstractComponentContainer.addComponent(AbstractComponentContainer.java:178)
	at com.vaadin.ui.CssLayout.addComponent(CssLayout.java:121)
	at io.jmix.ui.sys.ScreensImpl.showThisTabWindow(ScreensImpl.java:1195)
	at io.jmix.ui.sys.ScreensImpl.show(ScreensImpl.java:374)
	at io.jmix.ui.screen.Screen.show(Screen.java:306)
	at io.jmix.ui.action.list.EditAction.execute(EditAction.java:363)
	at io.jmix.ui.action.list.EditAction.actionPerform(EditAction.java:310)
	at io.jmix.ui.component.impl.AbstractTable.handleClickAction(AbstractTable.java:1358)
	at io.jmix.ui.component.impl.AbstractTable.lambda$initComponent$db766529$1(AbstractTable.java:1110)
	at jdk.internal.reflect.GeneratedMethodAccessor107.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
```

**Comment by alexbudarov** [comment]
Looks like it's not a bug.
As I've been told, lazy loading of local attributes doesn't work.

**Comment by andreysubbotin** [comment]
Yes, lazy loading works only for references.
