### ISSUE TITLE
Lazy loading of associations doesn't trigger in screen with non-read-only data context

### ISSUE THREAD

**Issue by alexbudarov** [Haulmont/jmix-data#24]
Project: attached
[llo2.zip](https://github.com/Haulmont/jmix-data/files/5629449/llo2.zip)

deck-browse.xml:
- fetch plan not set
- I have removed "readonly = true" from "data" tag

scenario
- launch app
- create Language
- create Deck, fill required fields
- reopen Deck browser

Associations are not lazy-loaded, plain old unfetched attribute error:
<details>
 <summary>Click to expand</summary>
 
```java
java.lang.IllegalStateException: Cannot get unfetched attribute [language] from detached object com.company.llo2.entity.Deck-1 [detached].
	at org.eclipse.persistence.internal.queries.EntityFetchGroup.onUnfetchedAttribute(EntityFetchGroup.java:100)
	at io.jmix.data.impl.JmixEntityFetchGroup.onUnfetchedAttribute(JmixEntityFetchGroup.java:67)
	at org.eclipse.persistence.internal.jpa.EntityManagerImpl.processUnfetchedAttribute(EntityManagerImpl.java:3027)
	at com.company.llo2.entity.Deck._persistence_checkFetched(Deck.java)
	at com.company.llo2.entity.Deck._persistence_get_language(Deck.java)
	at com.company.llo2.entity.Deck.getLanguage(Deck.java:112)
	at io.jmix.core.entity.BaseEntityEntry.getAttributeValue(BaseEntityEntry.java:73)
	at io.jmix.core.entity.EntityValues.getValue(EntityValues.java:90)
	at io.jmix.core.entity.EntityValues.getValueEx(EntityValues.java:121)
	at io.jmix.ui.component.data.table.ContainerTableItems.getItemValue(ContainerTableItems.java:116)
	at io.jmix.ui.component.table.TableItemWrapper.getPropertyValue(TableItemWrapper.java:81)
	at io.jmix.ui.component.table.TableItemPropertyWrapper.getValue(TableItemPropertyWrapper.java:37)
	at io.jmix.ui.component.impl.AbstractTable.formatCellValue(AbstractTable.java:1246)
	at io.jmix.ui.widget.JmixTable.formatPropertyValue(JmixTable.java:354)
	at io.jmix.ui.widget.JmixTable.getPropertyValue(JmixTable.java:269)
	at com.vaadin.v7.ui.Table.parseItemIdToCells(Table.java:2371)
	at com.vaadin.v7.ui.Table.getVisibleCellsNoCache(Table.java:2219)
	at com.vaadin.v7.ui.Table.refreshRenderedCells(Table.java:1762)
	at io.jmix.ui.widget.JmixGroupTable.refreshRenderedCells(JmixGroupTable.java:753)
	at com.vaadin.v7.ui.Table.attach(Table.java:4276)
	at com.vaadin.server.AbstractClientConnector.attach(AbstractClientConnector.java:643)
	at com.vaadin.ui.AbstractComponent.attach(AbstractComponent.java:670)
	at com.vaadin.server.AbstractClientConnector.attach(AbstractClientConnector.java:643)
	at com.vaadin.ui.AbstractComponent.attach(AbstractComponent.java:670)
	at com.vaadin.server.AbstractClientConnector.attach(AbstractClientConnector.java:643)
	at com.vaadin.ui.AbstractComponent.attach(AbstractComponent.java:670)
```
</details>

**Comment by andreysubbotin** [comment]
Fixed in Haulmont/jmix-data#19
