### ISSUE TITLE
IllegalStateException occurs when putting new entity with String id into HashMap

### ISSUE THREAD

**Issue by soraksh** [Haulmont/jmix-data#61]
Jmix version: 1.0.0-SNAPSHOT

1) Create entity with String ID
```
public class StringEntity {
    @Column(name = "ID", nullable = false)
    @Id
    private String id;

    @JmixGeneratedValue
    @Column(name = "UUID")
    private UUID uuid;
```
2) Create standard browser and editor screens for that entity
3) Try to create new entity instance using these screens

AR:
```
java.lang.IllegalStateException: Generated ID is null in com.company.jmixfronttest.entity.StringEntity-null [new]
	at io.jmix.core.EntityEntry.getGeneratedId(EntityEntry.java:41)
	at io.jmix.core.entity.BaseEntityEntry.hashCode(BaseEntityEntry.java:61)
	at io.jmix.core.impl.EntityInternals.hashCode(EntityInternals.java:78)
	at com.company.jmixfronttest.entity.StringEntity.hashCode(StringEntity.java)
	at java.base/java.util.HashMap.hash(HashMap.java:339)
	at java.base/java.util.HashMap.put(HashMap.java:607)
	at io.jmix.ui.model.impl.DataContextImpl.internalMerge(DataContextImpl.java:221)
	at io.jmix.ui.model.impl.DataContextImpl.merge(DataContextImpl.java:156)
	at io.jmix.ui.model.impl.DataContextImpl.merge(DataContextImpl.java:165)
	at io.jmix.ui.screen.StandardEditor.setupEntityToEdit(StandardEditor.java:212)
	at io.jmix.ui.screen.StandardEditor.beforeShow(StandardEditor.java:153)
	at io.jmix.core.common.event.EventHub.publish(EventHub.java:170)
	at io.jmix.ui.screen.Screen.fireEvent(Screen.java:124)
	at io.jmix.ui.screen.UiControllerUtils.fireEvent(UiControllerUtils.java:58)
	at io.jmix.ui.sys.ScreensImpl.fireScreenBeforeShowEvent(ScreensImpl.java:1356)
	at io.jmix.ui.sys.ScreensImpl.show(ScreensImpl.java:353)
	at io.jmix.ui.screen.Screen.show(Screen.java:306)
	at io.jmix.ui.action.list.CreateAction.execute(CreateAction.java:358)
	at io.jmix.ui.action.list.CreateAction.actionPerform(CreateAction.java:300)
...
```

**Comment by andreysubbotin** [comment]
Fixed in Haulmont/jmix-core#115
