### ISSUE TITLE
Table with Clob fields is not loaded in Oracle

### ISSUE THREAD

**Issue by TikhomirovME** [Haulmont/jmix-data#69]
When retrieving data from their CLOB field, when querying table data, T4VarcharAccessor is called (which does not have an implementation of the getClob method).
```
Caused by: java.sql.SQLException: Invalid column type: getCLOB not implemented for class oracle.jdbc.driver.T4CVarcharAccessor

                at oracle.jdbc.driver.GeneratedAccessor.getCLOB(GeneratedAccessor.java:1039)

Caused by: java.sql.SQLException: Invalid column type: getCLOB not implemented for class oracle.jdbc.driver.T4CVarcharAccessor

 

                at oracle.jdbc.driver.GeneratedStatement.getCLOB(GeneratedStatement.java:388)

                at oracle.jdbc.driver.GeneratedScrollableResultSet.getCLOB(GeneratedScrollableResultSet.java:531)

                at oracle.jdbc.driver.GeneratedScrollableResultSet.getClob(GeneratedScrollableResultSet.java:172)

                at oracle.jdbc.driver.GeneratedResultSet.getClob(GeneratedResultSet.java:536)

                at com.zaxxer.hikari.pool.HikariProxyResultSet.getClob(HikariProxyResultSet.java)

                at org.hibernate.type.descriptor.sql.ClobTypeDescriptor$1.doExtract(ClobTypeDescriptor.java:44)

                at org.hibernate.type.descriptor.sql.BasicExtractor.extract(BasicExtractor.java:47)

                at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:257)

                at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:253)

                at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:243)

                at org.hibernate.type.AbstractStandardBasicType.hydrate(AbstractStandardBasicType.java:329)

                at org.hibernate.persister.entity.AbstractEntityPersister.hydrate(AbstractEntityPersister.java:3135)

                at org.hibernate.loader.Loader.loadFromResultSet(Loader.java:1870)

                at org.hibernate.loader.Loader.hydrateEntityState(Loader.java:1798)

                at org.hibernate.loader.Loader.instanceNotYetLoaded(Loader.java:1771)

                at org.hibernate.loader.Loader.getRow(Loader.java:1623)

                at org.hibernate.loader.Loader.getRowFromResultSet(Loader.java:740)

                at org.hibernate.loader.Loader.getRowsFromResultSet(Loader.java:1039)

                at org.hibernate.loader.Loader.processResultSet(Loader.java:990)

                at org.hibernate.loader.Loader.doQuery(Loader.java:959)

                at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:349)

                at org.hibernate.loader.Loader.doList(Loader.java:2850)

                ... 127 common frames omitted
```

[Z_fbTuningVal.zip](https://github.com/Haulmont/jmix-data/files/6553321/Z_fbTuningVal.zip)

**Comment by plakhov** [comment]
The issue not reproduce
