### ISSUE TITLE
Lazy loading throws an exception if cross-datastore property is not in the fetchPlan

### ISSUE THREAD

**Issue by Flaurite** [Haulmont/jmix-data#95]
### Description
See forum [topic](https://forum.jmix.io/t/bulkedit-doesnt-work-with-cross-datastore-reference/704)

### Steps to reproduce
1. Download demo project: [demo.zip](https://github.com/Haulmont/jmix-data/files/7510395/demo.zip)

2. Open _Application -> GuestInfoes_ screen. GuestInfo contains reference to an entity (Person) from another datastore.
3. Select one GuestInfo and click on "Reload" button.
```
java.lang.RuntimeException: Unable to access value holder for property: person on entity com.company.master.entity.firststore.GuestInfo
	at io.jmix.eclipselink.impl.lazyloading.ValueHoldersSupport.getSingleValueHolder(ValueHoldersSupport.java:38)
	at io.jmix.eclipselink.impl.lazyloading.JpaLazyLoadingListener.processManyToOneValueHolder(JpaLazyLoadingListener.java:159)
	at io.jmix.eclipselink.impl.lazyloading.JpaLazyLoadingListener.processValueHolders(JpaLazyLoadingListener.java:109)
	at io.jmix.eclipselink.impl.lazyloading.JpaLazyLoadingListener.afterEntityLoad(JpaLazyLoadingListener.java:72)
	at io.jmix.core.datastore.DataStoreAfterEntityLoadEvent.sendTo(DataStoreAfterEntityLoadEvent.java:78)
	at io.jmix.core.datastore.AbstractDataStore.fireEvent(AbstractDataStore.java:343)
	at io.jmix.core.datastore.AbstractDataStore.loadList(AbstractDataStore.java:156)
	at io.jmix.core.impl.UnconstrainedDataManagerImpl.loadList(UnconstrainedDataManagerImpl.java:112)
	at com.company.master.screen.app.firststore.guestinfo.GuestInfoBrowse.onClickBtnClick(GuestInfoBrowse.java:54)
```

Another case from the forum is to use BulkEdit:
1. Do the same steps as previous case but then click on BulkEdit action
```
java.lang.RuntimeException: Unable to access value holder for property: person on entity com.company.master.entity.firststore.GuestInfo
	at io.jmix.eclipselink.impl.lazyloading.ValueHoldersSupport.getSingleValueHolder(ValueHoldersSupport.java:38)
	at io.jmix.eclipselink.impl.lazyloading.JpaLazyLoadingListener.processManyToOneValueHolder(JpaLazyLoadingListener.java:159)
	at io.jmix.eclipselink.impl.lazyloading.JpaLazyLoadingListener.processValueHolders(JpaLazyLoadingListener.java:109)
	at io.jmix.eclipselink.impl.lazyloading.JpaLazyLoadingListener.afterEntityLoad(JpaLazyLoadingListener.java:72)
	at io.jmix.core.datastore.DataStoreAfterEntityLoadEvent.sendTo(DataStoreAfterEntityLoadEvent.java:78)
	at io.jmix.core.datastore.AbstractDataStore.fireEvent(AbstractDataStore.java:343)
	at io.jmix.core.datastore.AbstractDataStore.loadList(AbstractDataStore.java:156)
	at io.jmix.core.impl.UnconstrainedDataManagerImpl.loadList(UnconstrainedDataManagerImpl.java:112)
	at io.jmix.ui.bulk.BulkEditorDataServiceImpl.reload(BulkEditorDataServiceImpl.java:50)
	at io.jmix.ui.app.bulk.BulkEditorWindow.loadItems(BulkEditorWindow.java:405)
	at io.jmix.ui.app.bulk.BulkEditorWindow.setBulkEditorContext(BulkEditorWindow.java:141)
	at io.jmix.ui.bulk.BulkEditors.buildEditor(BulkEditors.java:77)
	at io.jmix.ui.bulk.BulkEditorBuilder.create(BulkEditorBuilder.java:291)
	at io.jmix.ui.action.list.BulkEditAction.execute(BulkEditAction.java:328)
	at io.jmix.ui.action.list.BulkEditAction.actionPerform(BulkEditAction.java:255)
	at io.jmix.ui.component.impl.ButtonImpl.buttonClicked(ButtonImpl.java:75)
	at io.jmix.ui.widget.JmixButton.fireClick(JmixButton.java:77)
```

**Comment by reznikova21** [comment]
1.2.0-SNAPSHOT - verified
