### ISSUE TITLE
"Unable to access value holder for property" for @OneToOne relation with embedded entity

### ISSUE THREAD

**Issue by dtaimanov** [Haulmont/jmix-data#99]
#### Problem
CUBA project has been migrated to Jmix platform. It has Entity with embedded property and self-reference. Trying to edit entity with not null self-reference leads to exception: 
```
java.lang.RuntimeException: Unable to access value holder for property: homeAddress on entity com.haulmont.samples.ratlab.entity.stuff.Employee
	at io.jmix.eclipselink.impl.lazyloading.ValueHoldersSupport.getSingleValueHolder(ValueHoldersSupport.java:38)
	at io.jmix.eclipselink.impl.lazyloading.AbstractValueHolder.replaceLoadOptions(AbstractValueHolder.java:346)
	at io.jmix.eclipselink.impl.lazyloading.AbstractSingleValueHolder$SingleValuePropertyVisitor.visit(AbstractSingleValueHolder.java:51)
	at io.jmix.core.MetadataTools.internalTraverseAttributes(MetadataTools.java:1138)
	at io.jmix.core.MetadataTools.traverseAttributes(MetadataTools.java:898)
	at io.jmix.eclipselink.impl.lazyloading.AbstractSingleValueHolder.afterLoadValue(AbstractSingleValueHolder.java:38)
	at io.jmix.eclipselink.impl.lazyloading.AbstractValueHolder.getValue(AbstractValueHolder.java:276)
	at com.haulmont.samples.ratlab.entity.stuff.Employee._persistence_get_supervisor(Employee.java)
	at com.haulmont.samples.ratlab.entity.stuff.Employee.getSupervisor(Employee.java:67)
	at io.jmix.core.entity.BaseEntityEntry.getAttributeValue(BaseEntityEntry.java:74)
	at io.jmix.core.entity.EntityValues.getValue(EntityValues.java:94)
	at io.jmix.core.entity.EntityValues.getValueEx(EntityValues.java:125)
       ...

```

#### Steps:
1. Download and run [ratlab_vh_problem.zip](https://github.com/Haulmont/jmix-data/files/7608691/ratlab_vh_problem.zip)

2. Open Employees screen (there are two employees: one of them is supervisor for another. Both has adress fields filled):
![изображение.png](https://images.zenhubusercontent.com/5ed6636766d0991824e90fb6/a07e36c1-4d66-4dc1-9ea1-4209a070f8c2)
![изображение.png](https://images.zenhubusercontent.com/5ed6636766d0991824e90fb6/8315ba0a-1d85-4abe-ab3f-b820a278dd13)
3. Refresh table and try to edit entity with not empty "Supervisor" property.
**ER:** Editor screen openned
**AR:** Exception (see above)
![изображение.png](https://images.zenhubusercontent.com/5ed6636766d0991824e90fb6/d4b52e56-c6cc-4107-8788-8a38a4d104fa)

#### QA Notes:
Project has been updated to 1.2-SNAPSHOT

**Comment by reznikova21** [comment]
1.2.0-SNAPSHOT - verified

**Comment by smunir** [comment]
I am facing same issue in v1.1.3. Removing `@DependsOnProperties({"oneToManyEntity"})` in https://github.com/Haulmont/jmix-data/issues/99#issuecomment-977605883 works as workaround and stops the error.

**Comment by klaus7** [comment]
Yes, I also stumbled into the error already a few times with 1.1.3 - it was also "fixed" by removing DependsOnProperties
